packages:
  - 'packages/*'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
overrides:
  '@chassis-ui/css': link:../chassis-css
  '@chassis-ui/docs': link:../chassis-website/packages/docs
  '@chassis-ui/icons': link:../chassis-icons
  '@chassis-ui/tokens': link:../chassis-tokens
