import React, {
  createContext,
  DialogHTMLAttributes,
  forwardRef,
  useEffect,
  useId,
  useRef
} from 'react'
import classNames from 'classnames'

import { useDialogElement } from '../../hooks'

export interface DrawerProps extends Omit<
  DialogHTMLAttributes<HTMLDialogElement>,
  'onCancel' | 'onClose'
> {
  /**
   * Show a backdrop while the drawer is open. `'static'` blocks closing on backdrop click
   * (the drawer nudges instead).
   */
  backdrop?: boolean | 'static'
  /**
   * A string of all className you want applied to the base component.
   */
  className?: string
  /**
   * Size the height to the drawer's content instead of `--drawer-height`. Meaningful for
   * `placement="bottom"`.
   */
  fitContent?: boolean
  /**
   * Expand the panel to fill the viewport, animating in from the direction of `placement`.
   */
  fullscreen?: boolean
  /**
   * Disable the open/close transition entirely.
   */
  instant?: boolean
  /**
   * Closes the drawer when the escape key is pressed.
   */
  keyboard?: boolean
  /**
   * Callback fired when the drawer requests to be closed (escape, backdrop click, close button,
   * or another drawer opening).
   */
  onClose?: () => void
  /**
   * Callback fired when a close attempt is blocked (static backdrop click, or escape with `keyboard=false`).
   */
  onClosePrevented?: () => void
  /**
   * Callback fired after the exit transition completes and the drawer is fully hidden.
   */
  onHidden?: () => void
  /**
   * Callback fired when the drawer starts to open.
   */
  onShow?: () => void
  /**
   * Callback fired after the entry transition completes and the drawer is fully visible.
   */
  onShown?: () => void
  /**
   * Which viewport edge the panel slides in from. Always required — there is no default
   * off-screen transform without one.
   */
  placement: 'start' | 'end' | 'top' | 'bottom'
  /**
   * Renders as a drawer only below this breakpoint — inline as a flex container above it.
   */
  responsive?: 'small' | 'medium' | 'large' | 'xlarge' | '2xlarge'
  /**
   * Allow the page behind the drawer to scroll while it's open.
   */
  scroll?: boolean
  /**
   * Remove the inset gap, border radius, and border so the panel sits flush against the
   * viewport edge.
   */
  sheet?: boolean
  /**
   * Apply a frosted-glass background to the panel.
   */
  translucent?: boolean
  /**
   * Toggle the visibility of the drawer component.
   */
  visible?: boolean
}

export interface DrawerContextProps {
  /**
   * Requests the drawer be closed — fires `onClose`. Wire this to any element's `onClick`; see
   * `useDrawer`.
   */
  close: () => void
  /**
   * Id generated by `Drawer` and applied automatically by `DrawerTitle` to itself, so the
   * dialog's `aria-labelledby` resolves to it without any manual wiring.
   */
  titleId?: string
}

export const DrawerContext = createContext<DrawerContextProps>({ close: () => {} })

// Currently-open drawers, so opening one can auto-close any other open drawer
// ("When a second drawer opens while one is already open, the first closes automatically").
const openDrawers = new Set<{ dialog: HTMLDialogElement; close: () => void }>()

export const Drawer = forwardRef<HTMLDialogElement, DrawerProps>(
  (
    {
      children,
      backdrop = true,
      className,
      fitContent,
      fullscreen,
      instant,
      keyboard = true,
      onClose,
      onClosePrevented,
      onHidden,
      onShow,
      onShown,
      placement,
      responsive,
      scroll = false,
      sheet,
      translucent,
      visible,
      ...rest
    },
    ref
  ) => {
    const { close, dialogRef, forkedRef, handleBackdropClick, handleCancel, hiding, staticBounce } =
      useDialogElement({
        backdrop,
        instant,
        isModal: Boolean(backdrop) || !scroll,
        keyboard,
        onBeforeShow: (dialog) => {
          for (const entry of openDrawers) {
            if (entry.dialog !== dialog) entry.close()
          }
        },
        onClose,
        onClosePrevented,
        onHidden,
        onShow,
        onShown,
        ref,
        visible
      })

    const titleId = useId()

    const closeRef = useRef(close)
    closeRef.current = close

    // Register in the cross-instance registry so other drawers can auto-close this one.
    useEffect(() => {
      const dialog = dialogRef.current
      if (!dialog) return undefined
      const entry = { dialog, close: () => closeRef.current() }
      openDrawers.add(entry)
      return () => {
        openDrawers.delete(entry)
      }
    }, [dialogRef])

    // `hiding` has to stay on the class list for the whole exit transition: the native `open`
    // attribute — and with it, the `[class*="drawer"]:not([open], .hiding)` escape hatch
    // chassis-css's navbar styles use to suppress the drawer-flash transition when the navbar
    // itself crosses its `expand` breakpoint — would otherwise get stripped the instant `open`
    // is removed, which would also strip the *intentional* close transition this class exists
    // to protect.
    const _className = classNames(
      responsive ? `max-${responsive}:drawer` : 'drawer',
      `drawer-${placement}`,
      {
        fullscreen,
        sheet,
        translucent,
        instant,
        'drawer-fit-content': fitContent,
        nonmodal: !(Boolean(backdrop) || !scroll),
        static: staticBounce,
        hiding
      },
      className
    )

    return (
      <DrawerContext.Provider value={{ close, titleId }}>
        <dialog
          aria-labelledby={titleId}
          {...rest}
          className={_className}
          onCancel={handleCancel}
          onClick={handleBackdropClick}
          ref={forkedRef}
        >
          {children}
        </dialog>
      </DrawerContext.Provider>
    )
  }
)

Drawer.displayName = 'Drawer'
