import fs from 'node:fs'
import path from 'node:path'
import type { AstroIntegration } from 'astro'
import { createAutoImportPlugin } from '@chassis-ui/docs'
import { getDocsFsPath } from './path'

// Components from `@chassis-ui/docs` that are overridden by a local component of the
// same name, or that conflict with a `@chassis-ui/react` export of the same name.
// The local/react version always wins.
const excludedDocsShortcodes = new Set([
  'Icon.astro', // conflicts with the `Icon` export from `@chassis-ui/react`
  'Example.astro' // chassis-react has its own live-JSX `Example`, see `components/shortcodes/Example.astro`
])

const autoImportedComponentDirectories = [
  path.join(getDocsFsPath(), 'node_modules/@chassis-ui/docs/src/components/shortcodes'),
  path.join(getDocsFsPath(), 'src/components/shortcodes')
]

// Scan the shared `@chassis-ui/docs` shortcodes and the site's local shortcodes, and
// generate the type definitions + auto-import list for all of them. Local components
// always take precedence over `@chassis-ui/docs` components of the same name.
function scanComponents() {
  const components: string[] = []
  const definitions: string[] = []

  for (const directory of autoImportedComponentDirectories) {
    if (!fs.existsSync(directory)) continue

    const isDocsPackage = directory.includes('@chassis-ui/docs')

    for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
      if (!entry.isFile()) continue
      if (isDocsPackage && excludedDocsShortcodes.has(entry.name)) continue

      components.push(`${directory}/${entry.name}`)

      if (entry.name.endsWith('.astro')) {
        const importPath = isDocsPackage ? '@chassis-ui/docs/shortcodes' : '@shortcodes'
        definitions.push(
          `export const ${entry.name.replace('.astro', '')}: typeof import('${importPath}/${entry.name}').default`
        )
      }
    }
  }

  return { components, definitions }
}

// Astro integration that writes the auto-import type definitions file, and a remark
// plugin factory for injecting shortcode imports into every MDX file.
export function chassisAutoImportIntegration(): AstroIntegration {
  return {
    name: 'chassis-auto-import',
    hooks: {
      'astro:config:setup': () => {
        const { definitions } = scanComponents()

        fs.writeFileSync(
          './src/types/auto-import.d.ts',
          `/**
 * DO NOT EDIT THIS FILE MANUALLY.
 *
 * This file is automatically generated by the Chassis Astro Integration.
 * It contains the type definitions for the components that are auto imported in all pages.
 * @see packages/site/src/libs/shortcode.ts
 */
export declare global {
  ${definitions.join('\n  ')}
}
`
        )
      }
    }
  }
}

export function chassisAutoImportPlugin() {
  const { components } = scanComponents()
  return createAutoImportPlugin(components)
}
