import fs from 'node:fs'
import path from 'node:path'
import astroAutoImport from 'astro-auto-import'
import { getDocsFsPath } from './path'

// Components from @chassis-ui/docs that conflict with @chassis-ui/react exports.
const excludedShortcodes = new Set(['CxTable.astro'])
// A list of directories in `src/components` that contains components that will
// be auto imported in all pages for convenience.
// Note: adding a new component to one of the existing directories requires a
// restart of the dev server.
const autoImportedComponentDirectories = [
  path.join(getDocsFsPath(), 'node_modules/@chassis-ui/docs/src/components/shortcodes'),
  path.join(getDocsFsPath(), 'src/components/shortcodes')
]

// Generate the type definitions for all the auto imported components and write
// them to a file that will be included in the main `tsconfig.json` file to
// make the types available globally in the project.
export default function () {
  const autoImportedComponents: string[] = []
  const autoImportedComponentDefinitions: string[] = []

  for (const autoImportedComponentDirectory of autoImportedComponentDirectories) {
    const components = fs.readdirSync(autoImportedComponentDirectory, {
      withFileTypes: true
    })

    for (const component of components) {
      if (component.isFile() && !excludedShortcodes.has(component.name)) {
        autoImportedComponents.push(`${autoImportedComponentDirectory}/${component.name}`)

        if (component.name.endsWith('.astro')) {
          const importPath = autoImportedComponentDirectory.includes('@chassis-ui/docs')
            ? `@chassis-ui/docs/shortcodes`
            : `@shortcodes`
          autoImportedComponentDefinitions.push(
            `export const ${component.name.replace('.astro', '')}: typeof import('${importPath}/${component.name}').default`
          )
        }
      }
    }
  }

  const autoImportedComponentDefinition = `/**
 * DO NOT EDIT THIS FILE MANUALLY.
 *
 * This file is automatically generated by the Chassis Astro Integration.
 * It contains the type definitions for the components that are auto imported in all pages.
 * @see packages/site/src/libs/shortcode.ts
 */
export declare global {
  ${autoImportedComponentDefinitions.join('\n  ')}
}
`

  fs.writeFileSync('./src/types/auto-import.d.ts', autoImportedComponentDefinition)

  return astroAutoImport({
    imports: autoImportedComponents
  })
}
