import React, { createContext, DialogHTMLAttributes, forwardRef, useId } from 'react'
import classNames from 'classnames'

import { useDialogElement } from '../../hooks'

export interface ModalProps extends Omit<
  DialogHTMLAttributes<HTMLDialogElement>,
  'onCancel' | 'onClose'
> {
  /**
   * Show a backdrop while the modal is open. `'static'` blocks closing on backdrop click
   * (the modal bounces instead). `false` is intentionally not equivalent to `modal={false}` —
   * unlike `Drawer`, whose vanilla chassis-css counterpart derives modality from `backdrop`,
   * chassis-css's vanilla `Dialog` only ever reads `backdrop` to distinguish `'static'` from
   * everything else; `modal` alone decides `showModal()`/`show()`. This mirrors that faithfully
   * rather than reintroducing an inconsistency with the vendored behavior.
   */
  backdrop?: boolean | 'static'
  /**
   * A string of all className you want applied to the base component.
   */
  className?: string
  /**
   * Set modal to cover the entire user viewport. A breakpoint value goes fullscreen only
   * below that breakpoint.
   */
  fullscreen?: boolean | 'small' | 'medium' | 'large' | 'xlarge' | '2xlarge'
  /**
   * Disable the open/close transition entirely.
   */
  instant?: boolean
  /**
   * Closes the modal when the escape key is pressed.
   */
  keyboard?: boolean
  /**
   * Open with `showModal()` (top-layer, native backdrop). Set `false` to open with `show()`
   * instead — no backdrop, and the page behind the modal stays interactive.
   */
  modal?: boolean
  /**
   * Callback fired when the modal requests to be closed (escape, backdrop click, or close button).
   */
  onClose?: () => void
  /**
   * Callback fired when a close attempt is blocked (static backdrop click, or escape with `keyboard=false`).
   */
  onClosePrevented?: () => void
  /**
   * Callback fired after the exit transition completes and the modal is fully hidden.
   */
  onHidden?: () => void
  /**
   * Callback fired when the modal starts to open.
   */
  onShow?: () => void
  /**
   * Callback fired after the entry transition completes and the modal is fully visible.
   */
  onShown?: () => void
  /**
   * Create a scrollable modal — the header and footer stay fixed while the body scrolls.
   */
  scrollable?: boolean
  /**
   * Size the component small, large, or extra large.
   */
  size?: 'small' | 'large' | 'xlarge'
  /**
   * Toggle the visibility of modal component.
   */
  visible?: boolean
}

export interface ModalContextProps {
  /**
   * Requests the modal be closed — fires `onClose`. Wire this to any element's `onClick`; see
   * `useModal`.
   */
  close: () => void
  /**
   * Id generated by `Modal` and applied automatically by `ModalTitle` to itself, so the
   * dialog's `aria-labelledby` resolves to it without any manual wiring.
   */
  titleId?: string
}

export const ModalContext = createContext<ModalContextProps>({ close: () => {} })

export const Modal = forwardRef<HTMLDialogElement, ModalProps>(
  (
    {
      children,
      backdrop = true,
      className,
      fullscreen,
      instant,
      keyboard = true,
      modal = true,
      onClose,
      onClosePrevented,
      onHidden,
      onShow,
      onShown,
      scrollable,
      size,
      visible,
      ...rest
    },
    ref
  ) => {
    const { close, forkedRef, handleBackdropClick, handleCancel, hiding, staticBounce } =
      useDialogElement({
        backdrop,
        instant,
        isModal: modal,
        keyboard,
        onClose,
        onClosePrevented,
        onHidden,
        onShow,
        onShown,
        ref,
        visible
      })

    const titleId = useId()

    const _className = classNames(
      'modal',
      'dialog',
      {
        [typeof fullscreen === 'boolean' ? 'fullscreen' : `max-${fullscreen}:fullscreen`]:
          fullscreen,
        [`${size}`]: size,
        instant,
        nonmodal: !modal,
        scrollable,
        hiding,
        'dialog-static': staticBounce
      },
      className
    )

    return (
      <ModalContext.Provider value={{ close, titleId }}>
        <dialog
          aria-labelledby={titleId}
          {...rest}
          className={_className}
          onCancel={handleCancel}
          onClick={handleBackdropClick}
          ref={forkedRef}
        >
          {children}
        </dialog>
      </ModalContext.Provider>
    )
  }
)

Modal.displayName = 'Modal'
