import React, { ReactElement, ReactNode, useMemo } from 'react'
import classNames from 'classnames'
import {
  TableBody as AriaTableBody,
  TableBodyRenderProps,
  TableLoadMoreItem
} from 'react-aria-components'

// A unique value appended to `items` internally to represent the trailing "load more" row in
// react-aria-components' collection. `TableLoadMoreItem` has to be returned from the per-item
// render function like any other row — react-aria-components' `useCachedChildren` only supports
// EITHER `items` + a render function OR static `children`, never a mix of both in the same
// `children` prop, so a `<TableLoadMoreItem>` placed as a plain JSX sibling inside `<TableBody>`
// is silently dropped (or crashes, if `children` becomes an array mixing the render function in).
// Checked by reference (`item === LOADER_ITEM`), so it can never collide with a real `T` the way a
// `{ __loader: true }` marker object might if compared structurally. Its `id` matters too, not
// just its identity: react-aria-components derives each rendered item's React key from
// `rendered.props.id ?? item?.key ?? item?.id ?? <positional index>` (`useCachedChildren`) —
// `TableLoadMoreItem` doesn't accept an `id` prop itself, so without this object's own `id` the
// loader's key falls back to its position in the array, which collides with a real row whenever a
// row's own `id` happens to equal that count (e.g. a 2-item list with a row literally id `"2"`).
const LOADER_ITEM = { id: '__datagrid-body-loader__' }

interface DataGridBodyOwnProps {
  /**
   * A string of all className you want applied to the body row group.
   */
  className?: string
  /**
   * Values that should invalidate the row cache when using the `items`/render-function form of
   * `children` — e.g. a value from outside `items` that the render function reads. Without this,
   * changing that outside value won't re-render already-cached rows, since dynamic rows are only
   * rebuilt when `items` or `dependencies` change by reference, not on every parent re-render.
   */
  dependencies?: ReadonlyArray<unknown>
  /**
   * Content shown in place of rows when `items` is empty.
   */
  renderEmptyState?: (props: TableBodyRenderProps) => React.ReactNode
}

/**
 * The `items` + render-function form. `isLoading`/`loadingContent`/`onLoadMore` live here rather
 * than alongside the static form because the loader row is generated by appending to `items` and
 * rendering through that same function — there's no growing dataset to load more of, and nothing
 * to render the loader with, in a hand-written list of `DataGridRow` elements.
 */
interface DataGridBodyDynamicProps<T> {
  /**
   * A render function called once per item in `items`, returning that row's `DataGridRow`.
   */
  children: (item: T) => ReactElement
  /**
   * Whether more items are currently being fetched. Shows `loadingContent` in the loader row while
   * true, and — until this goes back to `false` — suppresses further `onLoadMore` calls, so one
   * scroll-into-view doesn't fire the callback again before the in-flight fetch resolves.
   */
  isLoading?: boolean
  /**
   * A list of row data objects, rendered via the function form of `children`.
   */
  items: Iterable<T>
  /**
   * Content rendered inside the loader row while `isLoading` is true, e.g. a spinner. Only takes
   * effect alongside `onLoadMore`.
   */
  loadingContent?: ReactNode
  /**
   * Called when the grid scrolls near its last row, so more data can be fetched and appended to
   * `items`. Pair with `isLoading` so a fetch already in flight isn't triggered again before it
   * resolves.
   */
  onLoadMore?: () => void
}

/** The static form: `DataGridRow` elements written out directly. */
interface DataGridBodyStaticProps {
  /**
   * `DataGridRow` elements.
   */
  children: ReactElement | ReactElement[]
  isLoading?: never
  items?: never
  loadingContent?: never
  onLoadMore?: never
}

/**
 * Split into a static and a dynamic form so the two can't be mixed: the loader row is appended to
 * `items` and rendered through `children`, so `onLoadMore` alongside a static list of elements used
 * to type-check and then throw at render ("children is not a function") the moment the loader row
 * came up.
 */
export type DataGridBodyProps<T> = DataGridBodyOwnProps &
  (DataGridBodyDynamicProps<T> | DataGridBodyStaticProps)

/**
 * Body row group for `DataGrid`, containing `DataGridRow`s. Unlike `Table`'s sub-parts, this
 * renders directly — it's a thin wrapper over react-aria-components' own `TableBody`.
 *
 * Always carries the `datagrid-body` class — see `DataGridHeader`'s equivalent note.
 */
export const DataGridBody = <T extends object>({
  children,
  className,
  dependencies,
  isLoading,
  items,
  loadingContent,
  onLoadMore,
  renderEmptyState
}: DataGridBodyProps<T>) => {
  const hasLoader = onLoadMore != null && items != null

  const itemsWithLoader = useMemo(() => {
    if (!hasLoader) return items
    return [...(items as Iterable<T>), LOADER_ITEM] as Iterable<T>
  }, [hasLoader, items])

  // react-aria-components caches each rendered row by item identity (see `dependencies`'s own doc
  // comment above) — the loader branch below reads `isLoading`/`onLoadMore`/`loadingContent`, none
  // of which are part of `items`, so without surfacing them here the cached loader row would keep
  // whatever `isLoading` value (and stale `onLoadMore` closure) was in scope the first time it
  // rendered, never picking up a later change.
  const dependenciesWithLoader = useMemo(
    () =>
      hasLoader ? [...(dependencies ?? []), isLoading, onLoadMore, loadingContent] : dependencies,
    [dependencies, hasLoader, isLoading, onLoadMore, loadingContent]
  )

  const bodyChildren = hasLoader
    ? (item: T) =>
        (item as unknown) === LOADER_ITEM ? (
          <TableLoadMoreItem
            className="datagrid-loader"
            isLoading={isLoading}
            // Suppresses re-triggering onLoadMore while a fetch is already in flight — the
            // underlying sentinel has no built-in debounce of its own and calls onLoadMore again
            // whenever it (re-)observes the sentinel still intersecting, e.g. after the collection
            // changes but the loader row hasn't yet scrolled out of view.
            onLoadMore={isLoading ? undefined : onLoadMore}
          >
            {loadingContent}
          </TableLoadMoreItem>
        ) : (
          // `hasLoader` implies the dynamic form of the props union, whose `children` is the
          // render function — `onLoadMore` isn't assignable alongside static children.
          (children as (item: T) => ReactElement)(item)
        )
    : children

  return (
    <AriaTableBody
      className={classNames('datagrid-body', className)}
      dependencies={dependenciesWithLoader}
      items={itemsWithLoader}
      renderEmptyState={renderEmptyState}
    >
      {bodyChildren}
    </AriaTableBody>
  )
}
